spring:
  datasource:
    url: jdbc:mysql://localhost:3306/funcionariodb?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  error:
    include-stacktrace: on_trace_param